# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18a40ae58565cb48673b83e4a2cdd3ad3a4bad2d12b30cbc48e2bfa46285233c9747bb155b24a42c470839ebec1b9512dc8d80b760196ee1a4d971f8c732c48d

test:
  secret_key_base: aeb787ea566251cf3033c0ba83408e47c37977393431502c8c08482a3c6b0ed2afe85c2dfb2fad62c9ea0ad9a019c2550781ecd7c0691ae144c2e6d2667bbb5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
